In [2]:
import numpy as np

In [3]:
#1.Create a null vector of size 10
null_vector =np.empty(10)
null_vector

array([2.12199579e-314, 0.00000000e+000, 2.12199579e-314, 4.94065646e-324,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

In [4]:
# How to find the memory size of an array
a = [1,3,6,9,7]
array = np.array(a)
print(f"memory size of the array is {array.itemsize}")
#print(len(array))

memory size of the array is 8


In [5]:
#Create a null vector of size 10 but the fifth value which is 1
null_10 = np.empty(10)
null_10[4] = 1
null_10

array([2.12199579e-314, 0.00000000e+000, 2.12199579e-314, 4.94065646e-324,
       1.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

In [6]:
#Create a vector with values ranging from 15 to 45
v = np.arange(15,46)
v

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [7]:
#Reverse a vector (The first element becomes last)
reverse_vector = np.array([1,2,3,4,5])
reverse_vector[::-1]

array([5, 4, 3, 2, 1])

In [8]:
#Write a NumPy program to add, subtract, multiply, divide arguments element-wise 7
arr = np.array([77,14,21,32,56])
def arithmetic(arr):
    print(np.add(arr,7))
    print(np.subtract(arr,7))
    print(np.divide(arr,7))
arithmetic(arr)

[84 21 28 39 63]
[70  7 14 25 49]
[11.          2.          3.          4.57142857  8.        ]


In [9]:
#Write a NumPy program to round elements of the array to the nearest integer 8.
arr = np.array([8.333,7.88,8.2,7.49,8.36])
round_to_8 = np.absolute(8,arr)
round_to_8

array([8., 8., 8., 8., 8.])

In [10]:
#Write a NumPy program to get the floor and ceiling values of the elements of a NumPy array
arr = np.array([3.436,9.45,1.36,5.36,10.3])
print(np.ceil(arr))
print(np.floor(arr))


[ 4. 10.  2.  6. 11.]
[ 3.  9.  1.  5. 10.]


In [11]:
#9. Write a NumPy program to calculate mean across dimensions, in a 2D NumPy array.
mean = np.array([[10,20,30,40,50],[10,20,30,40,50]])
print(np.mean(mean))

30.0


In [12]:
#What is the use of all and any function in numpy?

In [13]:
 #Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.array(np.arange(0,9)).reshape(3,3)
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
#How to reverse the columns of a 2D array?
reverse_2d_array = np.array(np.arange(1,10)).reshape(3,3)
print(f"metrix before reverse\n{reverse_2d_array}")
for i in range(3):
    print(f"reverse of column {i} = {reverse_2d_array[:,i][::-1]}")

metrix before reverse
[[1 2 3]
 [4 5 6]
 [7 8 9]]
reverse of column 0 = [7 4 1]
reverse of column 1 = [8 5 2]
reverse of column 2 = [9 6 3]


In [15]:
#How to reverse the rows of a 2D array?
_2d_array = np.array([6,7,8,3,4,5,0,1,2]).reshape(3,3)
print(f"metrix before reverse\n{_2d_array}")
for i in range(3):
    print(f"reverse of row {i} = {_2d_array[i][::-1]}")

metrix before reverse
[[6 7 8]
 [3 4 5]
 [0 1 2]]
reverse of row 0 = [8 7 6]
reverse of row 1 = [5 4 3]
reverse of row 2 = [2 1 0]


In [16]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
non_zero_ind = np.array([1,2,0,0,4,0])
for i in range(6):
    if non_zero_ind[i] != 0 :
        print(i)

0
1
4


In [17]:
#Write a NumPy program to compute the inverse of a given matrix
arri = np.array(([1,2,6],[3,5,6]))
np.unique_inverse(arri)

UniqueInverseResult(values=array([1, 2, 3, 5, 6]), inverse_indices=array([[0, 1, 4],
       [2, 3, 4]]))

In [18]:
pwd

'k:\\Data_analytics_assignments'

In [19]:
#18. Create a random vector of size 30 and find the mean value
rand_vector = np.array(np.random.random([30]))
print(f"mean of random vector is {rand_vector.mean()}")

mean of random vector is 0.49145898350728284


In [20]:
#19. How to extract all numbers between a given range from a NumPy array?
array = np.arange(1,31)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [21]:
#20.Create a 3x3x3 array with random values
arr_3x3x3 = np.array(np.random.random([3,3,3]))
arr_3x3x3

array([[[0.12072512, 0.53708846, 0.07306618],
        [0.00743677, 0.207481  , 0.43512059],
        [0.90269539, 0.4511013 , 0.63404153]],

       [[0.91920179, 0.41980307, 0.78433629],
        [0.30133794, 0.38016335, 0.67465742],
        [0.98621126, 0.49340144, 0.89869743]],

       [[0.32381156, 0.32197259, 0.97970972],
        [0.34248196, 0.29367824, 0.3341676 ],
        [0.76988148, 0.29430268, 0.11158283]]])

In [22]:
#21.Create a 10x10 array with random values and find the minimum and maximum values
arr_10x10 = np.array(np.random.random((10,10)))
print(f"minimum in array is {arr_10x10.min()}")
print(f"maximum in array is {arr_10x10.max()}")

minimum in array is 0.008961240742738075
maximum in array is 0.9999826753706449


In [23]:
#22. Create a 2d array with 1 on the border and 0 inside
arr = np.array([[1,1,1,1,1],[1,0,0,0,1],[1,0,0,0,1],[1,0,0,0,1],[1,0,0,0,1],[1,1,1,1,1]])
print(f"array is\n {arr}")

array is
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [24]:
#23.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
matrix_5x5 = np.array([[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[1,2,3,4,0]
])
matrix_5x5

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 2, 3, 4, 0]])

In [25]:
#24.Create a 3x3 identity matrix
identity = np.eye(3,3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
#Create a 8x8 matrix and fill it with a checkerboard pattern
'''[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]'''
matrix_8x8 = np.array([[0,1,0,1,0,1,0,1,],[1,0,1,0,1,0,1,0]]*4)
matrix_8x8

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [27]:
#26.Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
arr_5x3 = np.array([1,2,3,4,5])
arr_3x2 = np.array([3,6,9,])
arr_5x3

array([1, 2, 3, 4, 5])

In [28]:
#28. How to round away from zero a float array?


In [29]:
#29.How to find common values between the two arrays?
arr_one = np.array([1,9,7,6,4,5,6,12])
arr_two = np.array([1,6,8,4,5,3,12,10])
for i in arr_one:
    if i in arr_two:
        print(i)

False

In [37]:
#30.Create a vector of size 10 with values ranging from 0 to 1, both excluded
vector = np.array(np.random.random(10))
vector

array([0.03969156, 0.50518954, 0.96174105, 0.40647692, 0.88750755,
       0.5242036 , 0.06544665, 0.41377071, 0.96823273, 0.26385573])

In [102]:
#31.Create a random vector of size 10 and sort it
rand_vector = np.array(np.random.random(10))
print(rand_vector)
print(f"Vector after sort {np.sort(rand_vector)}")

[0.38763132 0.06122096 0.66356118 0.86645771 0.84063336 0.79533671
 0.88002153 0.13126109 0.79159713 0.70796294]
Vector after sort [0.06122096 0.13126109 0.38763132 0.66356118 0.70796294 0.79159713
 0.79533671 0.84063336 0.86645771 0.88002153]


In [115]:
#32. Create a 5x5 matrix with row values ranging from 0 to 4
matrix_5x5 = np.zeros((5,5))
matrix_5x5
np.arange(5)
matrix_5x5 += np.arange(5)
print(f"metrix after adding 0 to 4\n{matrix_5x5}")

metrix after adding 0 t0 4
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [172]:
#33.Consider two random arrays A and B, check if they are equal
a = np.array(np.random.randint(0,2,6))
b = np.array(np.random.randint(0,2,6))
print(a)
print(b)
if np.allclose(a,b):
    print("equal")
else:
    print("Not equal")

[1 0 0 0 0 1]
[1 0 0 0 0 1]
equal


In [190]:
#34.Create a random vector of size 10 and replace the maximum value by 0
np_random_vector = np.array(np.random.random(10))
print(np_random_vector)
max = np.max(np_random_vector)
print(max)
np_random_vector[np_random_vector.argmax()] = 0
np_random_vector

[0.13378845 0.65703989 0.49752857 0.7092002  0.6365049  0.58940388
 0.44706226 0.48672826 0.5121007  0.12101883]
0.7092001991666832


array([0.13378845, 0.65703989, 0.49752857, 0.        , 0.6365049 ,
       0.58940388, 0.44706226, 0.48672826, 0.5121007 , 0.12101883])

In [71]:
#35.How to find out multiple indices of an item?
arr = np.array([1,0,2,1,1,1,10,3,1])
indices = np.where(arr == 1)[0]
print("Indices",indices)

Indices [0 3 4 5 8]


In [ ]:
#36. What is the equivalent of enumerate for NumPy arrays?


In [107]:
#37. How to sort an array by the nth column?
array = np.array([[1,2,3,4,5],[5,9,7,6,10],[7,4,40,5,8]])
print(array)
c_sort = array[:,1]
c_sort.sort()
print(c_sort)

[[ 1  2  3  4  5]
 [ 5  9  7  6 10]
 [ 7  4 40  5  8]]
[2 4 9]


In [ ]:
#Swap to rows of an array


In [110]:
#39 How to compute the mean of a NumPy array?
mean_array = np.array([5,1,6,7,8])
print("Mean of array the array is",np.mean(mean_array))

Mean of array the array is 5.4


In [113]:
#40.How to compute the median of a NumPy array
med_array = np.array([1,2,3,4,5])
print("Median of the array is ",np.median(med_array))

Median of the array is  3.0


In [115]:
#41.How to compute the standard deviation of a NumPy array?
std_deviation = np.array([1,2,3,4,5,36])
print("Standard deviation is ",np.std(std_deviation))

Standard deviation is  12.365947867699695


In [120]:
#42. How to compute the mode of a NumPy array?


In [131]:
#43.How to print only 3 decimal places in a python NumPy array?
arr_round = np.array([1.3695,9.21456,7.3563])
np.round(arr_round,3)


array([1.37 , 9.215, 7.356])

In [135]:
#44.Write a NumPy program to compute the inverse of a given matrix
arr_inv = np.array([[1,6,9,7,4],[4,3,6,5,9],[1,4,2,7,0]])
print(arr_inv)
np.invert(arr_inv)

[[1 6 9 7 4]
 [4 3 6 5 9]
 [1 4 2 7 0]]


array([[ -2,  -7, -10,  -8,  -5],
       [ -5,  -4,  -7,  -6, -10],
       [ -2,  -5,  -3,  -8,  -1]])

In [ ]:
# 46. How to find the most frequent value in a NumPy array?


ValueError: cannot reshape array of size 6 into shape (3,3)

In [179]:
#47 How to convert 1D array to 3D array?
a = np.array([1,6,1,3,4,5,9,7,6],ndmin = 3)
a

array([[[1, 6, 1, 3, 4, 5, 9, 7, 6]]])

In [176]:
#48. How to convert 4D array to 2D array?
array_2d = np.array([[1,6,7,8,10],[1,6,9,7,4]],ndmin=4)
array_2d

array([[[[ 1,  6,  7,  8, 10],
         [ 1,  6,  9,  7,  4]]]])

In [182]:
#49. Create a Numpy array filled with all zeros
zeros = np.zeros((3,3))
zeros

numpy.ndarray

In [186]:
#50.Find the number of rows and columns of a given matrix using NumPy
#array = np.array([[1,0,7,9,4],[10,6,3,7,8]])

AttributeError: module 'numpy' has no attribute 'row'