In [1]:
import numpy as np

In [2]:
#-------Homework(2/1/2025)---------#
data_3d = np.array([ [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

In [3]:
data_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [4]:
#Extract the first matrix (all rows, all columns of the first layer).
data_3d[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#Extract the second matrix.
data_3d[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [6]:
#Extract the top-left 2x2 submatrix from the third matrix
data_3d[2,:2,:2]

array([[19, 20],
       [22, 23]])

In [7]:
#Extract the middle column of all matrices
data_3d[:,:,1]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [8]:
#Extract all elements from the first row of all matrices.
data_3d[:,0,:]

array([[ 1,  2,  3],
       [10, 11, 12],
       [19, 20, 21]])

In [9]:
#Extract the last column from the second row of all matrices.
data_3d[:,1,2]

array([ 6, 15, 24])

In [10]:
#Extract the first element of the first row from all matrices.
data_3d[:,0,0]

array([ 1, 10, 19])